### ISSUE TITLE
Use of the HAL impl?

### ISSUE THREAD

**Issue by therealprof** [Nercury/embedded-experiments#1]
Someone pointed me to your blog article, nice work!

I'm not sure you've noticed https://github.com/stm32-rs/stm32f1xx-hal yet which is a effort to create a universal HAL impl for all MCUs of the F1 family. It does not have explicit F100 support yet but that would be easy to add and we'd be happy to accept any contributions.

Some of the problems you're facing have already been solved and this crate should also allow you to use some peripherals without having to reinvent the wheel. Of course there's still a lot to do before it can be considered feature complete... ;)

Hope to see more of your experiments soon.

**Comment by Nercury** [comment]
Hi!

Yes, I have noticed it - but the intention was to keep it straightforward
at first, and start from low level implementation.

**Comment by Nercury** [comment]
Great work on the crate, but I am going to close this issue :)
